[simulation]
    name    = "/scratch/project_465002528/pjd/flux_tubes/tubes"
    engine  = "srpic"
    runtime = 10.0

    [simulation.domain]
        decomposition = [-1, -1, -1]

###! GRID
[grid]
    resolution = [256, 256, 256]
    extent     = [[0.0, 20.0], [-10.0, 10.0], [0.0, 20.0]]

    [grid.metric]
        metric = "minkowski"

    [grid.boundaries]
        fields    = [["MATCH", "MATCH"],   ["MATCH", "MATCH"],   ["PERIODIC"]]
        particles = [["ABSORB", "ABSORB"], ["ABSORB", "ABSORB"], ["PERIODIC"]] 

###! SCALES
[scales]
    larmor0    = 1.0
    skindepth0 = 1.0

###! ALGORITHMS
[algorithms]
    current_filters = 8

    [algorithms.timestep]
        CFL = 0.5

###! PARTICLES
[particles]
    ppc0 = 16.0

    [[particles.species]]
        label    = "e-"
        mass     = 1.0
        charge   = -1.0
        maxnpart = 1e8

    [[particles.species]]
        label    = "e+"
        mass     = 1.0
        charge   = 1.0
        maxnpart = 1e8

###! SETUP
[setup]
    #* Plasma
    B0           = 1.0          # B field normalisation
    sigma        = 1.0          # Magnetisation
    skin_depth   = 1.0          # Plasma skin depth
    background_T = 0.01         # Background temperature
    

    #* Flux Tubes
    beta_kick    = 0.2          # v/c --- E x B drift
    c_param      = 0.1          # Base guide field (check if is this needed?)
    radius_fraction  = 4.5      # Radius of the flux tubes

    #* Overall system
    init_J       = true         # Enforces J = curl(B) --- needed forforce free
    init_rho     = true         # Charge correction (ρ = ∇⋅E) to avoid charge imbalance noise
    init_ufl     = true         # E × B drift velocity of the particles
    single_tube  = false        # True = 2 flux tubes; False = 1 flux tube
    
    smooth_flds  = true         # Smooth fields
    nsmooth      = 16           # Number of smoothings

###! OUTPUT
[output]
    interval = 5
    format   = "BPFile"

    [output.fields]
        quantities = ["N", "B", "E", "J"]

    [output.particles]
        enable = false

    [output.spectra]
        enable = false

###! DIAGNOSTICS
[diagnostics]
    interval  = 50
    log_level = "WARNING"

###! CHECKPOINT
[checkpoint]
    interval = 5000
    keep     = 1