[simulation]
    name    = "/scratch/project_465002528/pjd/flux_tubes_CG/2D_512_test/tubes"
    engine  = "srpic"
    runtime = 1000.0

    [simulation.domain]
        decomposition = [-1, -1]


[grid]
    resolution = [2560, 2560]
    extent     = [[0.0, 512.0], [0.0, 512.0]]   #* Defined in terms of de

    [grid.metric]
        metric = "minkowski"

    [grid.boundaries]
        # fields    = [["MATCH", "MATCH"],   ["MATCH", "MATCH"]]
        # particles = [["ABSORB", "ABSORB"], ["ABSORB", "ABSORB"]] 
        fields    = [["PERIODIC"], ["PERIODIC"]]
        particles = [["PERIODIC"], ["PERIODIC"]]

[algorithms]
    current_filters = 0

    [algorithms.timestep]
        CFL = 0.5


[particles]
    ppc0 = 64.0

    [[particles.species]]
        label    = "e-"
        mass     = 1.0
        charge   = -1.0
        maxnpart = 2e8

    [[particles.species]]
        label    = "e+"
        mass     = 1.0
        charge   = 1.0
        maxnpart = 2e8


[scales]
    skindepth0 = 1.0                      #* de = skindepth0 = 1.0 code unit for pair plasma
    larmor0    = 0.1                      #* sigma = (skindepth0/larmor0)**2
    

[setup]
    #* Plasma
    background_temperature = 0.005        #* Background temperature (Debye length ~ sqrt(background_temperature))
    guide_field_floor      = 0.0001       #* Base/floor guide field (to avoid numerical instabilities)
    # nsmooth                = 16
    charge_correction      = false
    
    #* Flux Tubes
    kick_velocity          = 0.5          #* v/c --- E x B drift
    tube_radius            = 128.0        #* Radius of each flux tube (in de; choose it to be Lx/4)
    single_tube            = false        #* False = 2 flux tubes; True = 1 flux tube


[output]
    format   = "BPFile"

    [output.fields]
        quantities  = ["N", "B", "E", "J"]
        interval    = -1

    [output.particles]
        enable      = false

    [output.spectra]
        enable      = true
        e_min       = 1e-5
        e_max       = 1e4
        log_bins    = true
        n_bins      = 3600
        interval    = 100
    
    [output.stats]
        quantities  = ["B^2", "E^2", "ExB", "J.E", "Rho", "T00"]
        interval    = 50

[diagnostics]
    interval  = 500
    log_level = "WARNING"


[checkpoint]
    interval = 15000
    keep     = 1