[simulation]
    name    = "/scratch/project_465002528/pjd/flux_tubes_AV/L_804_201_dBy0.1_highres/tubes"
    engine  = "srpic"
    runtime = 1000.0                        #* t_max [ωpe⁻¹]

    [simulation.domain]
        decomposition = [-1, -1]


[grid]
    resolution = [6400, 3200]
    extent     = [[0.0, 804.0], [-201.0, 201.0]]        #* Defined in terms of de

    [grid.metric]
        metric = "minkowski"

    [grid.boundaries]
        fields    = [["PERIODIC"], ["CONDUCTOR", "CONDUCTOR"]]
        particles = [["PERIODIC"], ["REFLECT",   "REFLECT"  ]]


[algorithms]
    current_filters = 8

    [algorithms.timestep]
        CFL = 0.5


[particles]
    ppc0 = 128.0

    [[particles.species]]
        label    = "e-"
        mass     = 1.0
        charge   = -1.0
        maxnpart = 1e8

    [[particles.species]]
        label    = "e+"
        mass     = 1.0
        charge   = 1.0
        maxnpart = 1e8


[scales]
    skindepth0 = 1.0                        #* de = skindepth0 = 1.0 code unit for pair plasma
    larmor0    = 0.1                        #* sigma = (skindepth0/larmor0)**2; B0 = 1/larmor0


[setup]
    bg      = 0.0                           #* guide-field strength in normalised units
    eps     = 0.4                           #* Fadeev island parameter  ε ∈ (0,1);  ε=0 → Harris sheet
    sheet_L = 64.0                          #* current-layer half-thickness L [de];  Lx = 4π·L
    dby_frac    = -0.1                      #* perturbation amplitude from ∇·B = 0; |δBy| / b0 (DEFAULT = -0.1)
    temperature = 0.01                      #* kT / (mc²)


[output]
    format   = "BPFile"

    [output.fields]
        quantities = ["N", "B", "E", "J"]
        interval    = 250

    [output.particles]
        enable = false

    [output.spectra]
        enable      = true
        e_min       = 1e-5
        e_max       = 1e4
        log_bins    = true
        n_bins      = 3600
        interval    = 100
    
    [output.stats]
        quantities  = ["B^2", "E^2", "ExB", "J.E", "Rho", "T00"]
        interval    = 50


[diagnostics]
    interval  = 500
    log_level = "WARNING"


[checkpoint]
    interval = 10000
    keep     = 1